# Generated by Django 2.2.14 on 2022-11-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Item',
            new_name='item',
        ),
    ]
