# Generated by Django 2.2.14 on 2022-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221103_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
