# Generated by Django 2.2.14 on 2022-11-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='user',
        ),
    ]
